apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: auth-ingress-tls
spec:
  secretName: auth-ingress-tls
  issuerRef:
    name: hwc-letsencrypt-prod
    kind: ClusterIssuer
  commonName: auth.akeyless.asia
  dnsNames:
    - auth.akeyless.asia
    - auth-ro.akeyless.asia