apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: bis-ingress-tls
spec:
  secretName: bis-ingress-tls
  issuerRef:
    name: hwc-letsencrypt-prod
    kind: ClusterIssuer
  commonName: bis.akeyless.asia
  dnsNames:
    - bis.akeyless.asia
    - bis-ro.akeyless.asia