apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: hwc-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@akeyless.io
    privateKeySecretRef:
      name: hwc-letsencrypt-prod
    solvers:
      - selector:
        dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z0815679NUSMA9K9TGKO
            accessKeyID: AKIAXQU5TZUYYJQGSP6U
            secretAccessKeySecretRef:
              name: acme-route53
              key: secret-access-key
