apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rabbitmq-tls
  namespace: rabbitmq
spec:
  secretName: rabbitmq-tls
  issuerRef:
    name: hwc-letsencrypt-prod
    kind: ClusterIssuer
  commonName: mq.akeyless.asia
  dnsNames:
    - mq.akeyless.asia