apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubectl
  namespace: rabbits
spec:
  concurrencyPolicy: Forbid
  schedule: "/2 * * * *" # At minute 0 past every hour, change it.
  jobTemplate:
    spec:
#      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: rabbitmq
#          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'statefulset'
                - 'rabbitmq'
                - '-n'
                - 'rabbits'
          restartPolicy: Never
      backoffLimit: 6
  suspend: false