apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rabbitmq
  namespace: rabbits
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * 0" # At minute 0 past every hour, change it.
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: rabbitmq
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'delete'
                - 'pod'
                - 'rabbitmq-*'
                - '--force'
                - '--grace-period=0'