{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ template "rabbitmq-ha.chart" . }}
    release: {{ .Release.Name }}
data:
  enabled_plugins: |
    [
{{ .Values.extraPlugins | indent 6 }}

      rabbitmq_consistent_hash_exchange,
      rabbitmq_management,
      rabbitmq_peer_discovery_k8s,
      rabbitmq_auth_backend_oauth2

    ].

  rabbitmq.conf: |
    ## RabbitMQ configuration
    ## Ref: https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example

    ## Authentification
    {{- if .Values.rabbitmqAuth.enabled }}
{{ .Values.rabbitmqAuth.config | indent 4 }}
    {{- end }}

    default_user = {{ .Values.rabbitmqUsername }}
    default_pass = {{ .Values.rabbitmqPassword }}

    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.{{ .Values.clusterDomain }}
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 10

    # Set to false if automatic cleanup of absent nodes is desired.
    # This can be dangerous, see http://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup.
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = {{ .Values.rabbitmqClusterPartitionHandling }}

          {{- if eq .Values.rabbitmqUsername "guest" }}
    ## The default "guest" user is only permitted to access the server
    ## via a loopback interface (e.g. localhost)
    loopback_users.guest = false
          {{- end }}

    management.load_definitions = /etc/definitions/definitions.json

    ## Memory-based Flow Control threshold
    vm_memory_high_watermark.{{ .Values.rabbitmqMemoryHighWatermarkType }} = {{ .Values.rabbitmqMemoryHighWatermark }}

    ## AMQPS support
    {{- if .Values.rabbitmqAmqpsSupport.enabled }}
{{ .Values.rabbitmqAmqpsSupport.config | indent 4 }}
    {{- end }}

{{ .Values.extraConfig | indent 4 }}

{{- end }}

{{- if .Values.advancedConfig }}
  advanced.config: |
{{ .Values.advancedConfig | indent 4 }}
{{- end }}