{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app: {{ template "rabbitmq-ha.name" . }}
        chart: {{ template "rabbitmq-ha.chart" . }}
        release: {{ .Release.Name | quote }}
    name: {{ template "rabbitmq-ha.name" . }}
    namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    labels:
        app: {{ template "rabbitmq-ha.name" . }}
        chart: {{ template "rabbitmq-ha.chart" . }}
        release: {{ .Release.Name | quote }}
    name: {{ template "rabbitmq-ha.fullname" . }}
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: ["get"]
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        app: {{ template "rabbitmq-ha.name" . }}
        chart: {{ template "rabbitmq-ha.chart" . }}
        release: {{ .Release.Name | quote }}
    name: {{ template "rabbitmq-ha.fullname" . }}
    namespace: {{ .Release.Namespace }}
subjects:
    - kind: ServiceAccount
      name: {{ template "rabbitmq-ha.name" . }}
      namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ template "rabbitmq-ha.fullname" . }}
{{- end }}