{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "rabbitmq-ha.fullname" . }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ template "rabbitmq-ha.name" . }}
        chart: {{ template "rabbitmq-ha.chart" . }}
        release: "{{ .Release.Name }}"
type: Opaque
data:
        {{- $password := .Values.rabbitmqPassword | default (randAlphaNum 24 | nospace) -}}
        {{- $_ := set .Values "rabbitmqPassword" $password }}
    rabbitmq-username: {{ .Values.rabbitmqUsername | b64enc | quote }}
    rabbitmq-password: {{ .Values.rabbitmqPassword | b64enc | quote }}
    rabbitmq-erlang-cookie: {{ .Values.rabbitmqErlangCookie | default (randAlphaNum 32) | b64enc | quote }}
    {{ .Values.definitionsSource }}: {{ include "rabbitmq-ha.definitions" . | b64enc | quote }}
{{ end }}