apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ tpl (toYaml .Values.service.annotations) . | indent 4 }}
{{- end }}
  name: {{ template "rabbitmq-ha.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ template "rabbitmq-ha.chart" . }}
    release: {{ .Release.Name }}
spec:
        {{- if ne .Values.service.type "NodePort" }}
        {{- if and (eq .Values.service.type "LoadBalancer") (ne .Values.service.clusterIP "None") }}
    clusterIP: "{{ .Values.service.clusterIP }}"
        {{- end }}
        {{- end }}
        {{- if .Values.service.externalIPs }}
    externalIPs:
        {{ toYaml .Values.service.externalIPs | indent 4 }}
        {{- end }}
        {{- if .Values.service.loadBalancerIP }}
    loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
        {{- end }}
        {{- if .Values.service.externalTrafficPolicy }}
    externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
        {{- end }}
        {{- if .Values.service.loadBalancerSourceRanges }}
    loadBalancerSourceRanges:
        {{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
        {{- end }}
    ports:
        {{- if .Values.rabbitmqAmqpsSupport.enabled }}
        - name: amqps
          protocol: TCP
          port: {{ .Values.rabbitmqAmqpsSupport.amqpsNodePort }}
          targetPort: amqps
        {{- end }}

    selector:
        app: {{ template "rabbitmq-ha.name" . }}
        release: {{ .Release.Name }}
    type: {{ .Values.service.type }}