apiVersion: v1
kind: Service
metadata:
    name: {{ printf "%s-discovery" (include "rabbitmq-ha.fullname" .) | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ template "rabbitmq-ha.name" . }}
        chart: {{ template "rabbitmq-ha.chart" . }}
        release: {{ .Release.Name }}
spec:
    clusterIP: None
    ports:
        - name: http
          protocol: TCP
          port: {{ .Values.rabbitmqManagerPort }}
          targetPort: http
        - name: amqp
          protocol: TCP
          port: {{ .Values.rabbitmqNodePort }}
          targetPort: amqp
    publishNotReadyAddresses: true
    selector:
        app: {{ template "rabbitmq-ha.name" . }}
        release: {{ .Release.Name }}
    type: ClusterIP