apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: aws-letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@akeyless.io
    privateKeySecretRef:
      name: aws-letsencrypt-staging
    solvers:
      - selector:
        dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z08493902F3VF2QAXQCB5
            accessKeyID: AKIAXQU5TZUYSOBDTMNP
            secretAccessKeySecretRef:
              name: acme-route53
              key: secret-access-key